### ISSUE TITLE
Question about Vnnlib Syntax

### ISSUE THREAD

**Issue by hoy021** [Verified-Intelligence/Lyapunov_Stable_NN_Controllers#2]
Thank you for sharing your codebase! 
I'm not familiar with vnnlib files, and I got confused from the following lines about verifying Lyapunov condition.
```
; Verifying Lyapunov condition (output 0) holds (positive), and
; Lyapunov function (output 1) is less than the level set value.
(assert (or
  (and (<= Y_0 -1e-06))
  (and (<= Y_2 -3.000001))
  (and (>= Y_2 3.000001))
  (and (<= Y_3 -3.000001))
  (and (>= Y_3 3.000001))
))
(assert (<= Y_1 36.48387))
```
^([link](https://github.com/Verified-Intelligence/Lyapunov_Stable_NN_Controllers/blob/main/verification/specs/path_tracking_state_feedback_0.vnnlib#L27))

Is it saying `Y_0 <= -1e-6 or Y_2 <= -3 or Y_2 >= 3 or Y_3 <= -3 or Y_3 >= 3, AND Y_1 <= 36.48`? 
I thought Y_0 is the condition term ([link](https://github.com/Verified-Intelligence/Lyapunov_Stable_NN_Controllers/blob/main/neural_lyapunov_training/lyapunov.py#L318)) that needs to be non-negative? 
Or maybe I'm reading the syntax wrong? 

Thanks!

**Comment by shizhouxing** [comment]
Hi @hoy021, vnnlib format defines a counterexample which may satisfy the opposite of the Lyapunov condition (see https://www.vnnlib.org/). The verifier verifies the opposite of the specification defined in the vnnlib files.

**Comment by hoy021** [comment]
That makes sense for the first term (e.g. `Y_0 <= -1e-6 or Y_2 <= -3 or Y_2 >= 3 or Y_3 <= -3 or Y_3 >= 3`).
But don't we want to enforce `Y_1 <= 36.48`? based on the comment "Lyapunov function (output 1) is less than the level set value."?

Sorry if it's a silly question.
